version: '3'

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: am001541
      MYSQL_DATABASE: medecare
    volumes:
      - ./update.sql:/docker-entrypoint-initdb.d/update.sql

  app:
    image: node:latest
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
      - "8000:8000"
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - ./run-update.sh:/usr/src/app/run-update.sh
    depends_on:
      - mariadb
    environment:
      NODE_ENV: development
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: am001541
      DB_DATABASE: medecare
    command: sh -c "npm install && npm run dev:development && ./run-update.sh"
